### ISSUE TITLE
How to repeat Cross-domain Image Morphing

### ISSUE THREAD

**Issue by tg-bomze** [betterze/StyleAlign#12]
I saw in the README about cross-domain morphing between human and dogs faces, and I wanted to repeat it. I got a latent vector of a human face (.npz) and a latent vector of a dog face (.npz) using projector_z.py. Then I used the Truncation function from the MultiModal.py file to get a smooth transition between latent vectors. You provided many generator weights (for human faces, for dog faces, etc.), but I don't know which one to use to generate a picture between the two domains. If I use FFHQ, the morphing is between two human faces; if I use FFHQ-Dogs, it is between two dog faces. Please tell me how I can repeat the morphing between the two domains (FFHQ and Dogs).

**Comment by betterze** [comment]
Thank you for your interest in our work. All checkpoints could be download from [here](https://drive.google.com/drive/u/1/folders/1MqCHQ6Yx-eon-3fu1g_AGjpyAUmzH6Jy).

1. For cross-domain morphing between human and dogs faces, we need the parent model [FFHQ512](https://drive.google.com/file/d/1qT115GB4qR6yEn8MrlmJr0_V8Qvo1QmQ/view?usp=sharing) and the child model [FFHQ512_dog](https://drive.google.com/file/d/1qT115GB4qR6yEn8MrlmJr0_V8Qvo1QmQ/view?usp=sharing).

2. For cross-domain morphing, we need a good reconstruction for the inital human face and dog face (for the first and last frame), so we use [e4e](https://github.com/omertov/encoder4editing) encoder to encode them into w+ space, since w+ space has better reconstruction quality than z space. Z space is only good for image translation. You could download the e4e encoder for ffhq512 in [here](https://drive.google.com/file/d/1Asq4ngrjEJrFwO4CA8woZr2Rx1hsH8i9/view?usp=sharing) and ffhq512_dog in [here](https://drive.google.com/file/d/1pFaKmeQRdq8svTG3wIANkvufjgf0RekC/view?usp=sharing).

3. We need to morph the latent code and model weights simultaneously.

**Comment by tg-bomze** [comment]
Thank you very much. I will try to do as you described.

**Comment by betterze** [comment]
@tg-bomze I just upload the [Cross-domain Image Morphing codes](https://github.com/betterze/StyleAlign/blob/main/README.md#cross-domain-image-morphing).

**Comment by tg-bomze** [comment]
Thanks again. It works with e4e. Here is my Colab:
https://colab.research.google.com/github/tg-bomze/collection-of-notebooks/blob/master/PetBreeder.ipynb
